### ISSUE TITLE
Doesn't remove trailing spaces

### ISSUE THREAD

**Issue by yash-nisar** [verekia/remark-lint-no-trailing-spaces#2]
Command : `remark xyz.md`

`.remarkrc` file : 
```
{
  "plugins": {
    "lint": {
      "no-trailing-spaces": true
    }
  }
}
```

`remark-cli` version - `2.1.0`
`remark-lint` version - `5.4.0`
`remark-lint-no-trailing-spaces` version - `1.3.0`

File `xyz.md` : 
```
* xyz........
```
Note that the `.` stands for trailing whitespaces.

I've installed the package using the global installation method i.e. `npm insall -g remark-lint-no-trailing-spaces`

**Comment by yash-nisar** [comment]
CC @verekia @wooorm

**Comment by wooorm** [comment]
remark-lint rules don’t modify the input document. Are you asking about that, or about missing warnings?

**Comment by yash-nisar** [comment]
Sorry for misquoting it. I'm asking about missing warnings @wooorm

**Comment by wooorm** [comment]
In that case, probably ’cause of GH-1. I don’t think this rule works now.

**Comment by verekia** [comment]
It surely is why.
Sorry guys, I'm likely not going to take care of this for a while (or at all to be honest), since I have higher priority work to take care of :)
Don't use this plugin for now.

**Comment by Trott** [comment]
I believe this was fixed in https://github.com/verekia/remark-lint-no-trailing-spaces/commit/168d67737c2d662ff9bfae3190ba298de901b975. Please comment or re-open if I'm wrong about that.
