### ISSUE TITLE
Transferring ownership of the repo

### ISSUE THREAD

**Issue by verekia** [verekia/remark-lint-no-trailing-spaces#3]
Hey @evilebottnawi, wanna take a shot at updating the code to make it compatible with the latest `remark-lint`? I don't have time to take care of it, sorry :)

**Comment by evilebottnawi** [comment]
@verekia up, i have time do this in tomorrow, i think :smile: You can give me invite and i do all or i can send  PR :smile:

**Comment by verekia** [comment]
I added you as a collaborator :) When you have something working, I'll add you to NPM as well!

**Comment by evilebottnawi** [comment]
@verekia great!

**Comment by verekia** [comment]
@evilebottnawi I just published the new version to NPM :)

**Comment by verekia** [comment]
And initiated a transfer of the repo.

**Comment by nulltoken** [comment]
@verekia @evilebottnawi Has the transfer been finalized?

Who's now the official maintainer of this repository?

**Comment by Trott** [comment]
I'm not the owner, but I've been granted the necessary privileges to maintain it, so I'm going to close this out.

**Comment by wooorm** [comment]
@Trott Thanks for helping maintain this! Let me know if you need help and we at @remarkjs can chime in!
